name: Only allow merges to main from develop
on:
  pull_request:
    branches: [ main ]
jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if source branch is develop
        if: github.head_ref != 'develop'
        run: |
          echo "Pull request must come from 'develop' branch!"
          exit 1
      - name: Success
        run: echo "All good!"
